### PR TITLE
leet_1 solution

### PR DESCRIPTION
**Pull request by manbhasin**

### CODE REVIEW

**Comment by manbhasin** [comment]
@sashaaero Please review the PR asap . So that I can create more PR for your Problems . Thanks

**Comment by sashaaero** [comment]
@manbhasin Can you please provide `.py` file, not `.ipynb`?

**Comment by manbhasin** [comment]
> @manbhasin Can you please provide `.py` file, not `.ipynb`?

I have uploaded .py file but i am gettting conflicts because of same file name

**Comment by sashaaero** [comment]
@manbhasin sorry, but your solution is wrong. You should return list of values that sums up as target. Not print a message. Please fix this.
Also this problem is already solved. Use alternative name for this file, like `leet_1_2.py`.

**Comment by manbhasin** [comment]
> @manbhasin sorry, but your solution is wrong. You should return list of values that sums up as target. Not print a message. Please fix this.
> Also this problem is already solved. Use alternative name for this file, like `leet_1_2.py`.

I have updated my program and rename the file . Please Check

**Pull request merged**
